[package]
name = "TokenBoilerplate"
version = "0.0.1"
edition = "2024"

[dependencies]
World = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main" }

[addresses]
# Will be rewritten on publish
admin = "0x0"
TokenBoilerplate = "0x0"
